const GamesActionTypes = {
  EDIT_FULL_ARRAY_OF_GAMES: "EDIT_FULL_ARRAY_OF_GAMES",
  EDIT_DISPLAYED_ARRAY_OF_GAMES_FOR_SLOT_GAMES:
    "EDIT_DISPLAYED_ARRAY_OF_GAMES_FOR_SLOT_GAMES",
  EDIT_DISPLAYED_ARRAY_OF_GAMES_FOR_VIDEO_POKER:
    "EDIT_DISPLAYED_ARRAY_OF_GAMES_FOR_VIDEO_POKER",
  MOVE_GAMES_FOR_SLOT_GAMES: "MOVE_GAMES_FOR_SLOT_GAMES",
  MOVE_GAMES_FOR_VIDEO_POKER: "MOVE_GAMES_FOR_VIDEO_POKER",

  SET_FIRST_INDEX_OF_SLOT_GAMES: "SET_FIRST_INDEX_OF_SLOT_GAMES",
  SET_LAST_INDEX_OF_SLOT_GAMES: "SET_LAST_INDEX_OF_SLOT_GAMES",

  SET_FIRST_INDEX_OF_VIDEO_POKER: "SET_FIRST_INDEX_OF_VIDEO_POKER",
  SET_LAST_INDEX_OF_VIDEO_POKER: "SET_LAST_INDEX_OF_VIDEO_POKER",
  SET_FILTER_VALUE_FOR_SLOT_GAMES: "SET_FILTER_VALUE_FOR_SLOT_GAMES",
  SET_FILTER_VALUE_FOR_VIDEO_POKER: "SET_FILTER_VALUE_FOR_VIDEO_POKER",
};

export default GamesActionTypes;
